# Generated by Django 3.2.6 on 2023-03-12 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMALLS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=255, unique=True)),
                ('Latitude', models.CharField(max_length=255, unique=True)),
                ('Longitude', models.CharField(max_length=255, unique=True)),
                ('GPSHora', models.CharField(max_length=255, unique=True)),
                ('GPSMinuto', models.CharField(max_length=255, unique=True)),
                ('GPSSegundo', models.CharField(max_length=255, unique=True)),
                ('Acelerômetro1x', models.CharField(max_length=255, unique=True)),
                ('Acelerômetro1y', models.CharField(max_length=255, unique=True)),
                ('Acelerômetro1z', models.CharField(max_length=255, unique=True)),
                ('Acelerômetro2x', models.CharField(max_length=255, unique=True)),
                ('Acelerômetro2y', models.CharField(max_length=255, unique=True)),
                ('Acelerômetro2z', models.CharField(max_length=255, unique=True)),
                ('Umidade', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
